export {
  createInputProxy,
  buildLineProjection,
  coordinateToPosition,
  EditorView,
  getVisibleLineWindow,
  positionToLineOffset,
  positionToRect,
  renderCursorOverlay,
  renderMarkdownLines,
  renderPlainTextLineWindow,
  renderPlainTextLines,
  renderSelectionOverlay,
  scrollPositionIntoView,
  sourcePositionToVisualOffset,
  type ScrollPositionIntoViewConfig,
  visualOffsetToSourcePosition,
  type EditorMarkdownParseState,
  type LineProjection,
  type LineProjectionSegment,
  type ProjectionSegmentKind,
  type RenderMarkdownLinesOptions,
  type VisibleLineWindowConfig,
} from './editor-view'
export { SourceDocumentView, type SourceDocumentViewConfig } from './source-document-view'
export type {
  BlockView,
  CursorVisibilityOptions,
  Decoration,
  EditorViewConfig,
  EditorViewDispatch,
  EditorViewLike,
  PositionLineOffset,
  SearchHighlight,
  ViewCoordinate,
  ViewMetrics,
  ViewMode,
  ViewRect,
  ViewUpdate,
  VirtualViewportConfig,
} from './types'
