export {
  createInputProxy,
  buildLineProjection,
  coordinateToPosition,
  EditorView,
  positionToLineOffset,
  positionToRect,
  renderCursorOverlay,
  renderMarkdownLines,
  renderPlainTextLines,
  renderSelectionOverlay,
  scrollPositionIntoView,
  sourcePositionToVisualOffset,
  type ScrollPositionIntoViewConfig,
  visualOffsetToSourcePosition,
  type EditorMarkdownParseState,
  type LineProjection,
  type LineProjectionSegment,
  type ProjectionSegmentKind,
  type RenderMarkdownLinesOptions,
} from './editor-view'
export type {
  BlockView,
  CursorVisibilityOptions,
  Decoration,
  EditorViewConfig,
  EditorViewDispatch,
  EditorViewLike,
  PositionLineOffset,
  ViewCoordinate,
  ViewMetrics,
  ViewMode,
  ViewRect,
  ViewUpdate,
} from './types'
